#!/usr/bin/perl

# This script takes a simple VCALENDAR file as input on STDIN and produces a
# human readable text/plain representation of it on STDOUT
#
# It has been designed for use with mutt's auto_view config option, see the
# README file for more details

use strict;
use warnings;
use Data::ICal;
use Text::Autoformat;

my $body = eval { local $/ = undef; <> };
my $calendar = Data::ICal->new(data => $body);

foreach my $entry ( @{$calendar->{entries}} ) {
    my $properties;

    foreach my $property ( keys %{$entry->properties} ) {
        next unless defined $entry->property($property);
        $properties->{$property} = join(', ', map { $_->decoded_value } @{$entry->property($property)});
        if ( $property eq 'description' ) {
            $properties->{$property} = eval qq{"$properties->{$property}"};

            $properties->{$property} = autoformat $properties->{$property}, {
                all => 1,
                left => 15,
            };
            $properties->{$property} =~ s/^\s*// if defined $properties->{$property};
        }
        elsif ( $property =~ m{ \A dt (?: start | end ) \z }xms ) {
            if ( $properties->{$property} =~ m{ (\d\d\d\d)(\d\d)(\d\d)T(\d\d)(\d\d)(\d\d) }xms ) {
                $properties->{$property} = "$1-$2-$3 $4:$5";
            }
        }
    }

    if ( $entry->ical_entry_type eq 'VTIMEZONE' ) {
        unless ( defined $properties->{tzid} and $properties->{tzid} =~ m{Pacific/Auckland} ) {
            print "Timezone    : ", $properties->{tzid}, "\n";
            print "\n";
        }
    }
    elsif ( $entry->ical_entry_type eq 'VEVENT' ) {
        foreach my $key ( qw(summary BR description BR location organizer dtstart dtend) ) {
            if ( $key eq 'BR' ) {
                print "\n";
                next;
            }
            next unless defined $properties->{$key};
            printf "%-12s: %s\n", ucfirst $key, $properties->{$key};
        }
    }
    else {
        print "WARNING: Unknown entry type: ", $entry->ical_entry_type, "\n";
    }
}
